<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExamePratico.Application\ExamePratico.Application.csproj" />
    <ProjectReference Include="..\ExamePratico.Domain\ExamePratico.Domain.csproj" />
    <ProjectReference Include="..\ExamePratico.Infra.CrossCutting\ExamePratico.Infra.CrossCutting.csproj" />
    <ProjectReference Include="..\ExamePratico.Infra.Data\ExamePratico.Infra.Data.csproj" />
    <ProjectReference Include="..\ExamePratico.Services\ExamePratico.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
