// <auto-generated />
using System;
using ExamePratico.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamePratico.Infra.Data.Migrations
{
    [DbContext(typeof(ExamePraticoContext))]
    partial class ExamePraticoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExamePratico.Domain.Entities.Segurado", b =>
                {
                    b.Property<int>("SeguradoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeguradoId"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SeguradoId");

                    b.ToTable("Segurados", "dbo");

                    b.HasData(
                        new
                        {
                            SeguradoId = 1,
                            CPF = "123.456.789-00",
                            DataCadastro = new DateTime(2025, 8, 27, 4, 55, 41, 490, DateTimeKind.Local).AddTicks(1834),
                            DataNascimento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "João Silva"
                        },
                        new
                        {
                            SeguradoId = 2,
                            CPF = "987.654.321-00",
                            DataCadastro = new DateTime(2025, 8, 27, 4, 55, 41, 490, DateTimeKind.Local).AddTicks(1839),
                            DataNascimento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Maria Oliveira"
                        });
                });

            modelBuilder.Entity("ExamePratico.Domain.Entities.Seguro", b =>
                {
                    b.Property<int>("SeguroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeguroId"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Lucro")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MargemSeguranca")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SeguradoId")
                        .HasColumnType("int");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("int");

                    b.HasKey("SeguroId");

                    b.HasIndex("SeguradoId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Seguros", "dbo");
                });

            modelBuilder.Entity("ExamePratico.Domain.Entities.Veiculo", b =>
                {
                    b.Property<int>("VeiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VeiculoId"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ValorDoVeiculo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("VeiculoId");

                    b.ToTable("Veiculos", "dbo");

                    b.HasData(
                        new
                        {
                            VeiculoId = 1,
                            DataCadastro = new DateTime(2025, 8, 27, 4, 55, 41, 490, DateTimeKind.Local).AddTicks(1578),
                            Marca = "Toyota",
                            Modelo = "Corolla",
                            ValorDoVeiculo = 80000m
                        },
                        new
                        {
                            VeiculoId = 2,
                            DataCadastro = new DateTime(2025, 8, 27, 4, 55, 41, 490, DateTimeKind.Local).AddTicks(1616),
                            Marca = "Honda",
                            Modelo = "Civic",
                            ValorDoVeiculo = 85000m
                        },
                        new
                        {
                            VeiculoId = 3,
                            DataCadastro = new DateTime(2025, 8, 27, 4, 55, 41, 490, DateTimeKind.Local).AddTicks(1619),
                            Marca = "Ford",
                            Modelo = "Focus",
                            ValorDoVeiculo = 75000m
                        });
                });

            modelBuilder.Entity("ExamePratico.Domain.Entities.Seguro", b =>
                {
                    b.HasOne("ExamePratico.Domain.Entities.Segurado", "Segurado")
                        .WithMany()
                        .HasForeignKey("SeguradoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExamePratico.Domain.Entities.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Segurado");

                    b.Navigation("Veiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
